package de.rki.coronawarnapp.covidcertificate.exception

import de.rki.coronawarnapp.R

const val ERROR_MESSAGE_GENERIC = R.string.errors_generic_text_unknown_error_cause

// TODO change to correct error message once provided
const val ERROR_MESSAGE_TRY_AGAIN = ERROR_MESSAGE_GENERIC
const val ERROR_MESSAGE_DCC_NOT_SUPPORTED_BY_LAB = ERROR_MESSAGE_GENERIC
const val ERROR_MESSAGE_NO_NETWORK = ERROR_MESSAGE_GENERIC
const val ERROR_MESSAGE_E2E_ERROR_CALL_HOTLINE = ERROR_MESSAGE_GENERIC
const val ERROR_MESSAGE_TRY_AGAIN_DCC_NOT_AVAILABLE_YET = ERROR_MESSAGE_GENERIC
const val ERROR_MESSAGE_CLIENT_ERROR_CALL_HOTLINE = ERROR_MESSAGE_GENERIC
const val ERROR_MESSAGE_DCC_EXPIRED = ERROR_MESSAGE_GENERIC
