# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit APK through Firebase App Distribution"
  lane :firebaseAppDistribution do
     firebase_app_distribution(
           app: ENV["firebase_app_id"],
           apk_path: ENV["apk_path"],
           release_notes: "ithub.com/corona-warn-app/cwa-app-android/releases/tag/#{ENV["release_tag"]}",
           groups_file: "fastlane/groups.txt",
           service_credentials_file: "fastlane/service_credentials.json"
     )
  end
end
