package de.rki.coronawarnapp.util

enum class DeviceUIState {
    UNPAIRED,
    PAIRED_NO_RESULT,
    PAIRED_POSITIVE,
    PAIRED_POSITIVE_TELETAN,
    PAIRED_NEGATIVE,
    PAIRED_ERROR,
    PAIRED_REDEEMED,
    SUBMITTED_INITIAL,
    SUBMITTED_FINAL
}
