name: Android CI

on: [ push ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        commands: [':Corona-Warn-App:assembleDeviceRelease', ':Corona-Warn-App:detekt', ':Corona-Warn-App:assembleDeviceForTestersRelease', ':Corona-Warn-App:testDeviceReleaseUnitTest', ':Corona-Warn-App:testDeviceForTestersReleaseUnitTest', ':Corona-Warn-App:lintDeviceRelease', ':Corona-Warn-App:lintDeviceForTestersRelease', ':Corona-Warn-App:ktlintCheck']

    env:
      GRADLE_OPTS: -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Checks
        run: ./gradlew ${{ matrix.commands }}

      - name: Reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          path: Corona-Warn-App/build/reports
